#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************

Welcome to Workarea!

To learn more about our commerce platform, visit: https://developer.workarea.com

If this is your first time logging into the droplet, make sure you take
the following steps to finalize your Workarea installation:

1.) Edit configuration in /etc/profile.d/workarea.sh
2.) Seed the database by running \`bin/rails db:seed\` in /srv/shop

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
